### ISSUE TITLE
Update in hacs

### ISSUE THREAD

**Issue by Deedzy** [ankohanse/hass-dab-pumps#10]
**Describe the bug**
I updated the integration from hacs. Now everything is unavailable. It worked before the update.
I can login to dab to the live app so it seems I've been logged out in home assistant.
Should I uninstall the integration although I cannot see how to uninstall?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ankohanse** [comment]
As a workaround for this issue, could you please try the following:

Open the DAB Pumps integration, press '...' and choose remove. Then restart HA.
Go to integrations, choose 'add integration', select 'DAB pumps' and re- enter your credentials.

All sensor history will still be there after this process; it is how I update during development because I cannot update when my work in progress is not yet on GitHub, and I cannot put it on GitHub while it is still in progress...

Please let me know whether this workaround resolves your issue, it will give me clues about what went wrong during the update.

**Comment by Deedzy** [comment]
Thanks for the reply Anko,
   That didn't work so I deleted it and reinstalled it but then no devices
or entities?
Uninstalled and tried reinstalling the previous version but same result.

I'll wait and see if anyone else has trouble.


Regards,

Norman Deards
t: 0488 718 508
e: ***@***.***

**Comment by Deedzy** [comment]
I restored from last night's backup.

I'll wait before updating your dab integration still. 😁


Regards,

Norman Deards
t: 0488 718 508
e: ***@***.***

**Comment by ankohanse** [comment]
Odd, and unfortunately not much information for me to analyse why this happened.

1. Are there any errors or warnings showing in the logs at the time you did the upgrade and then reinstall (main menu -> logbook, or somewhere in the filesystem) ?

2. Also, what type of pump do you have?

3. Can you do a 'download diagnostic' from the downgraded version (I hope that version already had that functionality) and send me the resulting file?

**Comment by Deedzy** [comment]
I restored from backup but here is some info from before restoring.

2024-01-22 14:36:50.289 WARNING (SyncWorker_1) [homeassistant.loader] We
found a custom integration bureau_of_meteorology which has not been tested
by Home Assistant. This component might cause stability problems, be sure
to disable it if you experience issues with Home Assistant
2024-01-22 14:36:50.290 WARNING (SyncWorker_1) [homeassistant.loader] We
found a custom integration dabpumps which has not been tested by Home
Assistant. This component might cause stability problems, be sure to
disable it if you experience issues with Home Assistant
2024-01-22 14:36:50.290 WARNING (SyncWorker_1) [homeassistant.loader] We
found a custom integration hacs which has not been tested by Home
Assistant. This component might cause stability problems, be sure to
disable it if you experience issues with Home Assistant
2024-01-22 14:36:50.291 WARNING (SyncWorker_1) [homeassistant.loader] We
found a custom integration localtuya which has not been tested by Home
Assistant. This component might cause stability problems, be sure to
disable it if you experience issues with Home Assistant
2024-01-22 14:36:50.740 WARNING (MainThread)
[homeassistant.components.lovelace] Lovelace is running in storage mode.
Define resources via user interface
2024-01-22 14:37:27.695 WARNING (MainThread) [homeassistant.helpers.entity]
Updating state for calendar.ndeards_gmail_com (<class
'homeassistant.components.google.calendar.GoogleCalendarEntity'>) took
2.297 seconds. Please create a bug report at
https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+google%22
2024-01-22 14:37:29.327 WARNING (MainThread)
[homeassistant.components.songpal.media_player] [Sony Audio5097(
http://192.168.86.68:10000/sony)] Unable to connect
2024-01-22 14:37:29.355 WARNING (MainThread)
[homeassistant.components.media_player] Platform songpal not ready yet:
Unable to do POST request: Cannot connect to host 192.168.86.68:10000
ssl:default [Connect call failed ('192.168.86.68', 10000)]: None; Retrying
in background in 30 seconds
2024-01-22 14:37:29.362 ERROR (MainThread)
[homeassistant.components.camera] Error requesting stream: Camera not found
2024-01-22 14:37:29.466 WARNING (MainThread) [aioecowitt.server] Unhandled
sensor type heap value 26084
2024-01-22 14:37:30.971 WARNING (MainThread)
[homeassistant.components.media_player] Setup of media_player platform
dlna_dmr is taking over 10 seconds.
2024-01-22 14:37:35.457 ERROR (MainThread)
[homeassistant.components.sensor] Error while setting up dabpumps platform
for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py",
line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/dabpumps/sensor.py", line 54, in
async_setup_entry
    await helper.async_setup_entry(Platform.SENSOR, create_entity,
async_add_entities)
  File "/config/custom_components/dabpumps/helper.py", line 119, in
async_setup_entry
    entity = create_entity(self.coordinator, self.install_id, object_id,
device, params, status)

 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dabpumps/sensor.py", line 61, in
create_entity
    return DabPumpsSensor(coordinator, install_id, object_id, device,
params, status)

 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dabpumps/sensor.py", line 85, in __init__
    self._update_attributes(device, params, status, True)
  File "/config/custom_components/dabpumps/sensor.py", line 138, in
_update_attributes
    attr_unit = self._convert_to_unit(params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dabpumps/sensor.py", line 245, in
_convert_to_unit
    _LOGGER.warn(f"DAB Pumps encountered a unit or measurement '{unit}'
that may not be supported by Home Assistant. Please contact the integration
developer to have this resolved.")
                                                                 ^^^^
NameError: name 'unit' is not defined
2024-01-22 14:37:56.475 WARNING (MainThread) [zigpy.application] Zigbee
channel 15 utilization is 85.82%!
2024-01-22 14:37:56.476 WARNING (MainThread) [zigpy.application] If you are
having problems joining new devices, are missing sensor updates, or have
issues keeping devices joined, ensure your coordinator is away from
interference sources such as USB 3.0 devices, SSDs, WiFi routers, etc.
2024-01-22 14:37:57.175 ERROR (MainThread) [homeassistant.helpers.event]
Error while processing template:
Template<template=({{(states('sensor.headermean') | float ) | round(2) }})
renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line
1984, in forgiving_float_filter
    return float(value)
           ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line
567, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line
2305, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py",
line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py",
line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line
1987, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line
1625, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unavailable' when
rendering template '{{(states('sensor.headermean') | float ) | round(2) }}'
but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line
693, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line
569, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float
got invalid input 'unavailable' when rendering template
'{{(states('sensor.headermean') | float ) | round(2) }}' but no default was
specified
2024-01-22 14:37:57.184 ERROR (MainThread)
[homeassistant.components.template.template_entity]
TemplateError('ValueError: Template error: float got invalid input
'unavailable' when rendering template '{{(states('sensor.headermean') |
float ) | round(2) }}' but no default was specified') while processing
template 'Template<template=({{(states('sensor.headermean') | float ) |
round(2) }}) renders=4>' for attribute '_attr_native_value' in entity
'sensor.template_test_water_pressure'
2024-01-22 14:37:57.186 ERROR (MainThread) [homeassistant.helpers.event]
Error while processing template:
Template<template=({{((states('sensor.headermean') | float - 1.5) * 400 |
float ) | round (0) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line
1984, in forgiving_float_filter
    return float(value)
           ^^^^^^^^^^^^


Regards,

Norman Deards
t: 0488 718 508
e: ***@***.***

**Comment by Deedzy** [comment]
The pump is an Esybox mini3

**Comment by ankohanse** [comment]
Thank you, that trace is very helpful and precisely indicates where I made a coding mistake. 

Will try to come with a fixed version in the next days and will add a comment in this issue once it is available

**Comment by ankohanse** [comment]
A new version v2024.01.2 is now available.
Please let me know if you still encounter issues with this new version.
