### ISSUE TITLE
Modify sensor.devicename_totalenergy to be available for energy dashboard

### ISSUE THREAD

**Issue by nicopret1** [ankohanse/hass-dab-pumps#16]
**Is your feature request related to a problem? Please describe.**
I want to add the energy used by my pump to the energy dashboard. However, the only energy entity that is currently available to add as individual device is the sensor.devicename_actual_period_energy_counter. Since this counter will reset at month-end it will not work correctly with the HA energy dashboard. I believe the correct sensor to add should be: sensor.devicename_totalenergy. This senor is, however, not currently available as per the below screenshot and I suspect it might be that the attribute "state_class: total_increasing" is not defined for this sensor.

![Screenshot 2024-03-09 at 11 11 59](https://github.com/ankohanse/hass-dab-pumps/assets/130547447/b0240a2c-9a52-400b-90b3-19fd681d3c25)

**Describe the solution you'd like**
I want to add the sensor.devicename_totalenergy to my energy dashboard to correctly report the energy usage for this device in the energy dashboard.

**Comment by ankohanse** [comment]
@nicopret1 
I see that there is another sensor available in the ESybox.mini 3 that seems related to TotalEnergy: PartialEnergy
Would you be able to tell how that one behaves in the DConnect App/Website.

Just so that if I change TotalEnergy to be a state_class: total_increasing, than I might as well do the same for PartialEnergy. Unless the behavior is completely different ofcourse.

Note that according to the documentation, sensors with state_class total_increasing are actually allowed to decrease in value (usually a reset to 0). This is interpreted as the start of a new meter cycle (i.e. a new day, month or even a year).

**Comment by nicopret1** [comment]
@ankohanse there is an option in System Management to reset the partial energy counter, but not for TotalEnergy. I therefore suggest that you only add TotalEnergy. 
![Screenshot 2024-03-10 at 12 43 31](https://github.com/ankohanse/hass-dab-pumps/assets/130547447/a5639235-0691-4f39-97dd-e1c99bb4ad97)

I already "fixed" it on my side by moving TotalEnergy from keys_none = [TotalEnergy,] to keys_ti = [TotalEnergy,] in entity_base.py. :-)

As a side note, I see I can also enable/disable the pump from System Management. Would you be able to also add a switch entity for that? I would like to add an automation to automatically disable the pump when my water tank runs low to prevent the pump from running dry.

If a total_increasing counter is reset, one will have to manually correct the stats. I suspect the reason for being able to reset total_increasing counter is for a scenario where a "meter" is replaced.

Currently my PartialEnergy = Total Energy, but that is only because I have not performed a reset.
![Screenshot 2024-03-10 at 12 44 38](https://github.com/ankohanse/hass-dab-pumps/assets/130547447/92f5ec02-81a6-459b-8b3a-14a0760af0b2)

I'm not sure if you're familiar with the HA Energy Dashboard? One can easily view the daily, monthly, yearly, etc. statistics as per the below:
![Screenshot 2024-03-10 at 13 02 36](https://github.com/ankohanse/hass-dab-pumps/assets/130547447/24d29f21-7b73-4040-b9e9-65539199ba1c)

**Comment by ankohanse** [comment]
Just published 2024.03.5 which will let TotalEnergy use state_class total_increasing so it can be used on the Energy dashboard.
Decided to apply the same change to PartialEnergy, as it may be of use to others.
The change you made in your local code was indeed the only change needed.

I'll createa separate change request for the pump enable/disable.
