### ISSUE TITLE
Add Pump Enable/Disable as a switch

### ISSUE THREAD

**Issue by ankohanse** [ankohanse/hass-dab-pumps#17]
[Added on behalf of  @nicopret1]
DConnect System Management on an ESybox mini 3 shows the option for Pump Enable/Disable. 
Would you be able to also add a switch entity for that? I would like to add an automation to automatically disable the pump when my water tank runs low to prevent the pump from running dry.

**Comment by ankohanse** [comment]
Released as v2024.03.6

Wanted it slightly separate from the exising 'Controls' group, which hold settings intended to be changed by the 'customer', like PowerShower and SleepMode.
So moved this into the 'Configuration' group, as it is a setting intended for 'installers' according to the DAB Pumps installations json. In the future other entities like 'Firmware Update' might also get exposed here.
![image](https://github.com/ankohanse/hass-dab-pumps/assets/11971893/dd8b754d-91c1-4699-8564-a5be042ca775)

**Comment by nicopret1** [comment]
Thank you @ankohanse. The enable/disable functionality is available, but do not work when I set the enable/disable option. I see the following error message in  my dashboard:
[
<img width="561" alt="Screenshot 2024-03-11 at 15 39 07" src="https://github.com/ankohanse/hass-dab-pumps/assets/130547447/1a6cde06-0b1c-4572-bc95-272972181bb3">
](url)


and the following in the system log:
`File "/config/custom_components/dabpumps/coordinator.py", line 224, in async_modify_data
2024-03-11 15:38:13.143 WARNING (MainThread) [custom_components.dabpumps.coordinator] Retry 3 in 5 seconds. Unable to authenticate to dconnect.dabpumps.com. Please re-check your username and password in your configuration!
2024-03-11 15:38:24.970 WARNING (MainThread) [custom_components.dabpumps.coordinator] Retry 4 in 5 seconds. Unable to authenticate to dconnect.dabpumps.com. Please re-check your username and password in your configuration!
2024-03-11 15:38:36.933 WARNING (MainThread) [custom_components.dabpumps.coordinator] Retry 5 in 5 seconds. Unable to authenticate to dconnect.dabpumps.com. Please re-check your username and password in your configuration!
2024-03-11 15:38:48.711 WARNING (MainThread) [custom_components.dabpumps.coordinator] Retry 6 in 5 seconds. Unable to authenticate to dconnect.dabpumps.com. Please re-check your username and password in your configuration!
2024-03-11 15:38:56.119 WARNING (MainThread) [custom_components.dabpumps.coordinator] Retry 7 in 5 seconds. Unable to authenticate to dconnect.dabpumps.com. Please re-check your username and password in your configuration!
File "/config/custom_components/dabpumps/coordinator.py", line 220, in async_modify_data
File "/config/custom_components/dabpumps/coordinator.py", line 311, in _async_change_device_status
File "/config/custom_components/dabpumps/coordinator.py", line 219, in async_modify_data
File "/config/custom_components/dabpumps/select.py", line 170, in async_select_option
File "/config/custom_components/dabpumps/coordinator.py", line 224, in async_modify_data`


 The other "issue" I noticed is Pump enable/disable = unavailable which displays as per the below in the diagnostic group
<img width="383" alt="Screenshot 2024-03-11 at 15 28 15" src="https://github.com/ankohanse/hass-dab-pumps/assets/130547447/58cb3160-4edd-44c5-96c1-4542310f9d37">

**Comment by Djavdeteg** [comment]
I confirm. Have the same errors.

**Comment by ankohanse** [comment]
Odd, no issues in the trace on my system and I see the pump enable/disable confirmed when I login to the DConnect web portal. Will investigate further what could cause this to behave different on an ESybox mini 3.
![image](https://github.com/ankohanse/hass-dab-pumps/assets/11971893/66a814b0-d7ad-4e2a-9d25-a5e702b55044)

The unavailable 'Pump Enable/Disable' under diagnostics is the old (non-changable) sensor entry with unique_id 'sensor.<device name>_pumpdisable'. The new one under 'Configuration' will have an unique_id 'select.<device name>_pumpdisable' since it now has become a 'select' entity instead of a sensor entity. 
You can click on the old disabled one, press the 'settings' (gear icon on top right) and choose 'delete' to get rid of it.

**Comment by Djavdeteg** [comment]
Well, I found it. Access level "Customer" is not sufficient for enable/disable action.

**Comment by ankohanse** [comment]
@Djavdeteg   you beat me to it, was just starting to suspect that. Unlike the PowerShower and SleepMode actions which can be done as 'Customer', the Pump Enable/Disable requires 'Installer' rights. This role is set when you create the account in DConnect on their website.

Could not see an option anywhere to change the rights later on once an account is created. Or did I miss it somewhere?

**Comment by ankohanse** [comment]
I want to find a way to determine in the code whether the role is set to 'Customer' or to 'Installer' (or one of the other roles). Knowing that, I can show or hide the Pump Enable/Disable button.

I spotted a 'Get User Info' call made from the DConnect website, but do not quitte understand the meaning of all returned data yet. No clear recognizable 'role' attribute in there. So would be good to see what that returns on various systems. 
I have extended my diagnostics code to retrieve more information about this call, this will be included in v2024.03.7 which I will release later today.

@Djavdeteg and @nicopret1 or any other user that wants to help, could you please (if possible before you change your user role from 'customer' to 'installer'):
- install v2024.03.7. Restart of Home Assistant may be needed.
- Use the 'Pump Enable/Disable' once (even though it will fail, doing the call will collect valuable diagnistics for me)
- Go to the DAB Pumps integration page and into your device.
- Choose 'DownLoad Diagnostics'
- Email the resulting file to me via 'info at anko dot co dot nz' and let me know if your user was a 'customer' or an 'installer'
![image](https://github.com/ankohanse/hass-dab-pumps/assets/11971893/21cb3cfe-2124-48b3-9564-6a0bfda790a1)

Thank you, also on behalf of future users of the integration!

**Comment by nicopret1** [comment]
Thank you @Djavdeteg and @ankohanse for all your efforts. Happy to test and forward diagnostics as requested.

**Comment by ankohanse** [comment]
Solution now published as v2024.03.8:

> Use user role (Customer or Installer) to determine if an entity is allowed to be changed.
Depending on the role, render the entity as a (read-only) sensor, or as a (changeable) number, select or switch.
>
> For example, 'Pump Enable/Disable' is only allowed to be changed when user has Installer role.
>
> Note: the Customer/Installer role is independent from whether the user is registered as 'End User' or 'Professional' on the DConnect DAB Pumps website. The role is set per installation and is shown in the 'Manage Permissions' section on the 'Installation Settings' page for the installation.

**Comment by nicopret1** [comment]
Thank you @ankohanse I confirm that all working well on my side as well with the user set as installer
