### ISSUE TITLE
[BUG] - Integration configuration for polling interval not working

### ISSUE THREAD

**Issue by hernaj** [ankohanse/hass-dab-pumps#20]
**Describe the bug**
Polling interval option for the sensors is failing when updating the default value. If you try to change the default polling interval from 20 seconds to another value, the change will not be applied and an exception will be raised.

**To Reproduce**
1. Go to DAB integration configuration.
2. Click on configure.
3. Change polling interval to another value.
4. See error.

**Expected behavior**
Value shall be changed.

**Comment by hernaj** [comment]
Solved by this PR: https://github.com/ankohanse/hass-dab-pumps/pull/21
Tested directly changing the HASS config files for the integration.

**Comment by ankohanse** [comment]
Thank you for resolving this. I've merged your changes into the main branch.
