### ISSUE TITLE
Update parameters directly from HA

### ISSUE THREAD

**Issue by bmorfin** [ankohanse/hass-dab-pumps#28]
Congratulations for this nice HA integration.

But I would suggest to have the possibility to update every "updatable pump parameters" in HA directly. 

I've seen that such a request was already raised (as issue #9) in Jan 2021, requesting to have 'inputs' for the parameters in both groups 'Extra Comfort' and 'Setpoint'.

But the scope was limited to the 'Extra comfort group' only and not to the 'Setpoint group'.
 
Would it be possible to reconsider this limitation and to extend the inputs to the other entry parameters ?

**Comment by ankohanse** [comment]
Done, for parameters in group 'Setpoint'.
Included in v2024.05.1 which was released just now.

Am a bit hesitant to also open up parameters in groups 'installer' and 'system management' for updates. Would like to see a clear use case for that first as those parameters probably only will be set at installation time.

**Comment by bmorfin** [comment]
Hello Anko,

 

That’s great ! But I’ve noticed that the validation range for the pressure SP does not seem correct…

 



 

Can you please have a look.

 

Thanks

Best Regards,

Bernard.

De : Anko Hanse ***@***.***> 
Envoyé : mardi 7 mai 2024 04:33
À : ankohanse/hass-dab-pumps ***@***.***>
Cc : bmorfin ***@***.***>; Author ***@***.***>
Objet : Re: [ankohanse/hass-dab-pumps] Update parameters directly from HA (Issue #28)

 

Done, for parameters in group 'Setpoint'.
Included in v2024.05.1 which was released just now.

Am a bit hesitant to also open up parameters in groups 'installer' and 'system management' for updates. Would like to see a clear use case for that first as those parameters probably only will be set at installation time.
