### ISSUE TITLE
Setup parameters validation range error

### ISSUE THREAD

**Issue by bmorfin** [ankohanse/hass-dab-pumps#29]
Hello,

the validation ranges for the setup parameters are not correct :

- SP_SetpointPressurePsi            the range should be 1.0 to 5.5 (instead of 0.1 - 0.6)
- RP_PressureFallToRestartPsi     the range should be 0.1 to 1.0 (instead of 0.0 - 0.1)

So these 2 values cannot be updated in Home Assistant.

Can you please check ?

**Comment by ankohanse** [comment]
Was already looking into it, as these values have no min or max value specified on my pump (ESybox).
For an ESybox Mini3 I see the following config definition from DAB Pumps:
                         {
                          "name": "SP_SetpointPressureBar",
                          "type": "measure",
                          "family": "tachimeter",
                          "group": "Setpoint",
                          ...
                          "unit": "bar",
                          "weight": 0.1,
                          "min": 1,
                          "max": 5.5,
                          "groupApp": "Setpoint",
                          "groupPosApp": 10
                        },
                        {
                          "name": "RP_PressureFallToRestartBar",
                          "type": "measure",
                          "family": "graph",
                          "group": "Setpoint",
                          ...
                          "unit": "bar",
                          "weight": 0.1,
                          "min": 0.1,
                          "max": 1,
                          "groupApp": "Advanced",
                          "groupPosApp": 30
                        },

So I need to allow the code to work in case there is no min and max specified, but also I might have misinterpreted how min and max work (on the displayed value, not the value corrected with weigt, 5.5 bar is stored as value 55)

**Comment by ankohanse** [comment]
Should be fixed now in v2024.05.2

Please let me know if you run into any other issues
