### ISSUE TITLE
Entity sensor.zisterne_fluid_remain is using state class 'measurement' which is impossible

### ISSUE THREAD

**Issue by Bascht74** [ankohanse/hass-dab-pumps#36]
**Describe the bug**
ogger: homeassistant.components.sensor
Quelle: components/sensor/__init__.py:569
Integration: Sensor ([Dokumentation](https://www.home-assistant.io/integrations/sensor), [Probleme](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
Erstmals aufgetreten: 17:38:45 (5 Vorkommnisse)
Zuletzt protokolliert: 17:38:48

Entity sensor.zisterne_fluid_remain (<class 'custom_components.dabpumps.sensor.DabPumpsSensor'>) is using state class 'measurement' which is impossible considering device class ('water') it is using; expected None or one of 'total', 'total_increasing'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/ankohanse/hass-dab-pumps/issues

**To Reproduce**
./.

**Expected behavior**
no error message

**Screenshots**
<img width="658" alt="image" src="https://github.com/user-attachments/assets/1c275ce4-70c4-4fe3-ab0a-6671a3df3626">

**Additional context**
I find it odd that measurement is not OK with HA...

**Comment by ankohanse** [comment]
Should now be fixed in v2024.08.1 which I have just released.
