### ISSUE TITLE
sensor.esybox_mini_last_period_flow_counter_gall is using state class 'measurement' which is impossible

### ISSUE THREAD

**Issue by jrkk0925** [ankohanse/hass-dab-pumps#37]
**Describe the bug**
Whenever I restart home assistant the following error is being logged:
Entity sensor.esybox_mini_last_period_flow_counter_gall (<class 'custom_components.dabpumps.sensor.DabPumpsSensor'>) is using state class 'measurement' which is impossible considering device class ('water') it is using; expected None or one of 'total', 'total_increasing'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/ankohanse/hass-dab-pumps/issues

**To Reproduce**
1. Restart home assistant
2. Click on settings > system > logs

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version:

**Comment by ankohanse** [comment]
Easy fix, now resolved in v2024.08.2 which I just published
