### ISSUE TITLE
DAB Live to H2D

### ISSUE THREAD

**Issue by BradleyFord** [ankohanse/hass-dab-pumps#39]
It seems that DAB is moving to a new platform called H2D... I dont have any information on it, just wanted to alert you.

https://h2d.mobi/end-user/

**Comment by ankohanse** [comment]
Thanks for that. Indeed a thing to keep an eye on.
It may only have minor consequenses for the DAB Pumps integration, or it may completely render it inoperable. All depends on how the new apps retrieve their information from the DAB backend servers. If needed I will analyse the new apps behaviors and adapt the integration.
