### ISSUE TITLE
some sensors should be binary_sensors

### ISSUE THREAD

**Issue by Bascht74** [ankohanse/hass-dab-pumps#4]
**Describe the bug**
Right now they are normal sensors with with the state "active" or "inactive". 

**Expected behavior**

The following two sensors of the dconnect box 2 should be binary sensory, they can be only "on" oder "off":
- DConnect Box 2 In1
- DConnect Box 2 Out1 

**Additional context**
Thx for this integration! So far I used the HA rest sensor for integrating the pump but this way it is much easier...
The API seemed to be stable, even with the new UI design in 2022/2023 the json stuff didn't change.

**Comment by ankohanse** [comment]
Thank you for your excellen suggestiont. 
At the moment I am only doing small fixes on my initial version of the integration, but am planning for some changes with bigger code impact for a release by the end of January 2024. Will try to incorporate the binary_sensors into that one.

**Comment by ankohanse** [comment]
This has been included in release v2024.01.1 which is available now.
Sensors that should be a binary_sensor are automatically detected based on their possible values. 

Please let me know if you notice any issues.

**Comment by Bascht74** [comment]
Great!
