### ISSUE TITLE
Closes httpx.Client

### ISSUE THREAD

**Issue by domenicoblanco** [ankohanse/hass-dab-pumps#41]
**Describe the bug**
A new warning appears every time I reboot my hass server, this error appears in the logs:
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 00:15:19 (1 occurrences)
Last logged: 00:15:19

Detected that custom integration 'dabpumps' closes the Home Assistant httpx client at custom_components/dabpumps/api.py, line 281: await self._client.aclose(), please create a bug report at https://github.com/ankohanse/hass-dab-pumps/issues

 
**To Reproduce**
1. Go to Settings after a reboot
2. Click on System
3. Click on Log

**Expected behavior**
That the httpx client isn't closed

**Additional context**
 - Home Assistant version: 2024.9.3
 - Server OS: OpenMediaVault 7.4.8-1 (Debian based)

**Comment by ankohanse** [comment]
Thanks for reporting this, will look into it

**Comment by domenicoblanco** [comment]
Thanks!

**Comment by ankohanse** [comment]
This should be fixed in release v2024.10.1 that I have published just now.
