### ISSUE TITLE
Sockets not closing

### ISSUE THREAD

**Issue by domenicoblanco** [ankohanse/hass-dab-pumps#43]
**Describe the bug**
Since the last update I had some problems while starting some other containers in my server. 
Looking with `netstat -a` I found a lot of sockets open (939) with the `CLOSE_WAIT` state such as in the attached image.

**To Reproduce**
1. Log into the server
2. Run `sudo netstat -a | grep dabcs` 
3. See error

**Expected behavior**
That there aren't so many sockets open

**Screenshots**
<img width="1193" alt="Screenshot 2024-10-10 alle 18 11 57" src="https://github.com/user-attachments/assets/cfaff7f2-7eeb-4e54-a3d4-f1251dd5247f">

**Server (please complete the following information):**
 - OS: OpenMediaVault 7.4.9-2 (Debian based)
 - Home Assistant version: 2024.10.1

**Additional context**
Probably is not related but in the HASS logs sometimes appears also this error:
`2024-10-09 10:01:37.676 ERROR (MainThread) [custom_components.dabpumps.coordinator] Error fetching DAB Pumps data: Timeout while communicating with API:`

**Comment by ankohanse** [comment]
Thanks for reporting this issue.
It definately is related to the previous issue reported by you (#41). Bit of a conundrum, if I close the sockets then HA issues a warning, if I do not close them them you will eventually run out of sockets...

Will investigate for possible solutions!

**Comment by domenicoblanco** [comment]
Before discovering this integration, I was trying to build mine and I remember that I found easier to switch from httpx to aiohttp as was the same used by HASS.
Long story short, I was able to create a session for my plugin and obtain data without HASS complaining. I haven't tested it with recent versions but could be worth to give it a shot.

Just for reference, my plugin was based on the apis module that I wrote inspecting the [DAB Live!](https://github.com/domenicoblanco/dab-live-api) app.

**Comment by ankohanse** [comment]
I think I figured out a better solution: keep using the same client session instead of creating a new session for each (re-)login. Will run it through more tests over the weekend and publish as new release when I am completely happy with it.

Your apis module looks like a good start. My implementation has matured quitte a lot from a similar start and now handles other account types (DAB Live and DConnect), auto detection of scaling for values (some are times 1000 or divided by 1000), auto detection of units, auto detection and translation of entity names, etc.

**Comment by domenicoblanco** [comment]
Yeah, it wasn't an alternative but just an example on how I did it.
Hope to be able to test it soon and thanks c:

**Comment by ankohanse** [comment]
A fis is now published as 2024.10.2.
Please let me know if you still find any issues.

**Comment by ankohanse** [comment]
Follow up:
As a test, I've ported the code to use aiohttp instead of httpx. Preliminary results seem to indicate that aiohttp behaves better (only one open port instead of 3 or 4) and seems to give less timeout issues. Will do some more testing and then release that extra change.

**Comment by domenicoblanco** [comment]
That's interesting!
Thanks for giving it a try
