### ISSUE TITLE
Disable pump option

### ISSUE THREAD

**Issue by Jeroen2000** [ankohanse/hass-dab-pumps#49]
**Is your feature request related to a problem? Please describe.**
I'd like to disable the pump if flood condition is detected by a flood sensor. This can be a real live saver as it would otherwise potentially dump > 5000L of water in the house in case a pipe of filter breaks.
Alternatively, without a flood sensor, one could just consider an abnormally long pump running event as a reason to shut it down.

**Describe the solution you'd like**
Implement the "Pump enable/disable" setting present in the DConnect app

**Comment by ankohanse** [comment]
Pump Enable/Disable is already a changeble entity, see issue [issue 17](https://github.com/ankohanse/hass-dab-pumps/issues/17)
However, it will only present itself that way if the account you use for the DabPumps integration has 'Installer' role, not 'Customer' role.

![image](https://github.com/user-attachments/assets/a0aa7b75-e266-4ebe-84b6-ebaed58d7037)

Note that the Customer/Installer role is independent from whether the user is registered as 'End User' or 'Professional' on the DConnect DAB Pumps website (that one is only used for marketing emails). The role is set per installation and is shown on the DAB DConnect website in the 'Manage Permissions' section on the 'Installation Settings' page for the installation.

Could you please check your user has the 'Installer' role?
If your role shows up as 'Customer', you can remove the user rights from the installation (does not delete the user itself) and then add it again to the installation with 'Installer'

**Comment by ankohanse** [comment]
Glad to help and to hear that everything is working as expected.

**Comment by sdesalve** [comment]
> Pump Enable/Disable is already a changeble entity, see issue [issue 17](https://github.com/ankohanse/hass-dab-pumps/issues/17) However, it will only present itself that way if the account you use for the DabPumps integration has 'Installer' role, not 'Customer' role.
> 
> ![image](https://github.com/user-attachments/assets/a0aa7b75-e266-4ebe-84b6-ebaed58d7037)
> 
> Note that the Customer/Installer role is independent from whether the user is registered as 'End User' or 'Professional' on the DConnect DAB Pumps website (that one is only used for marketing emails). The role is set per installation and is shown on the DAB DConnect website in the 'Manage Permissions' section on the 'Installation Settings' page for the installation.
> 
> Could you please check your user has the 'Installer' role? If your role shows up as 'Customer', you can remove the user rights from the installation (does not delete the user itself) and then add it again to the installation with 'Installer'

Hi @ankohanse ,

I've tried to add another user as installer, I've registered other mail as professional but in Manage Permission section, if I want to add another user, I cannot choose any other option than CUSTOMER 

![Image](https://github.com/user-attachments/assets/09f2f500-9b64-427b-b752-f684ac335528)

How I can add an installer user?
Best regards 
SDeSalve
