### ISSUE TITLE
Add Fluid_Remain for DAB Esybox Diver

### ISSUE THREAD

**Issue by Bascht74** [ankohanse/hass-dab-pumps#5]
**Is your feature request related to a problem? Please describe.**
I have an Diver and the fluid add-on 
https://www.completepumpsupplies.co.uk/dab-nfc-water-level-sensor-for-e-sybox-diver

**Describe the solution you'd like**
Get the sensor for that.

**Describe alternatives you've considered**
./.

**Additional context**
here is the JSON-Output for the Fluid_Remain...
Maybe there are more sensors missing. You said something about usind installation.json in the other issue, I am not sure if it will fix this.

  "res": "OK",
  "result": "OK",
  "status_validity": 15,
  "statusts": "2023-12-23T18:47:41.808Z",
  "lastreceived": "2023-12-23T18:47:41.812Z",
  "refresh": 2000,
  "servertime": 1703357286332,
  "status": "{\"AE_AntiLock\":\"1\",\"AF_AntiFreeze\":\"1\",\"AY_AntiCycling\":\"1\",\"Actual_Period_Energy_Counter\":\"55\",\"Actual_Period_Flow_Counter\":\"3142\",\"Actual_Period_Flow_Counter_Gall\":\"h\",\"C1_PumpPhaseCurrent\":\"0\",\"Error1\":\"0\",\"Error2\":\"0\",\"Error3\":\"0\",\"Error4\":\"0\",\"Error5\":\"0\",\"Error6\":\"0\",\"Error7\":\"0\",\"Error8\":\"0\",\"ErrorTime1\":\"0\",\"ErrorTime2\":\"0\",\"ErrorTime3\":\"0\",\"ErrorTime4\":\"0\",\"ErrorTime5\":\"0\",\"ErrorTime6\":\"0\",\"ErrorTime7\":\"0\",\"ErrorTime8\":\"0\",\"FirmwareStatus\":\"1\",\"FloatEnable\":\"0\",\"FloatSwitchStatus\":\"255\",\"FluidLevel\":\"1058\",\"Fluid_Remain\":\"6052\",\"Fluid_Remain_inch\":\"h\",\"ForceDownload\":\"0\",\"GI_IntegralGainElasticPlant\":\"h\",\"GI_IntegralGainRigidPlant\":\"11\",\"GP_ProportionalGainElasticPlant\":\"h\",\"GP_ProportionalGainRigidPlant\":\"5\",\"HO_PowerOnHours\":\"21458\",\"HO_PumpRunHours\":\"452\",\"HvBoardId\":\"8\",\"HvFwVersion\":\"1.0.4\",\"Last_Period_Energy_Counter\":\"21\",\"Last_Period_Flow_Counter\":\"2294\",\"Last_Period_Flow_Counter_Gall\":\"h\",\"LvFwVersion\":\"1.4.29\",\"OD_PlantType\":\"1\",\"PO_InputPower\":\"0\",\"PowerShowerBoost\":\"20\",\"PowerShowerCommand\":\"0\",\"PowerShowerCountdown\":\"h\",\"PowerShowerDuration\":\"1800\",\"PowerShowerPressureBar\":\"48\",\"PowerShowerPressurePsi\":\"h\",\"PressureTarget\":\"h\",\"ProductType\":\"101\",\"PumpDisable\":\"0\",\"PumpStatus\":\"0\",\"PumpStatusTime\":\"1703354414\",\"RM_MaximumSpeed\":\"5200\",\"RP_PressureFallToRestartBar\":\"10\",\"RP_PressureFallToRestartPsi\":\"h\",\"RS_RotatingSpeed\":\"0\",\"SP_SetpointPressureBar\":\"40\",\"SP_SetpointPressurePsi\":\"h\",\"SV_SupplyVoltage\":\"236\",\"Saving\":\"55\",\"SleepModeCountdown\":\"h\",\"SleepModeDuration\":\"25200\",\"SleepModeEnable\":\"0\",\"SleepModePressureBar\":\"28\",\"SleepModePressurePsi\":\"h\",\"SleepModeReduction\":\"30\",\"SleepModeStartTime\":\"82800\",\"StartNumber\":\"41822\",\"SystemStatus\":\"0\",\"T2_SwitchOffDelay\":\"8\",\"TB_DryRunDetectTime\":\"30\",\"TE_HeatsinkTemperatureC\":\"14\",\"TankFill\":\"62\",\"TankMinLev\":\"15\",\"TankMinLev_inch\":\"h\",\"Tank_L1_D1\":\"270\",\"Tank_L1_D1_inch\":\"h\",\"Tank_L2\":\"0\",\"Tank_L2_inch\":\"h\",\"UpdateFirmware\":\"h\",\"UpdateProgress\":\"h\",\"UpdateType\":\"0\",\"VF_FlowGall\":\"h\",\"VF_FlowLiter\":\"0\",\"VP_PressureBar\":\"33\",\"VP_PressurePsi\":\"h\",\"FluidLevel_inch\":\"h\"}"
}

**Comment by ankohanse** [comment]
Thank you for sending in this request, It is very helpfull for me to receive input from owners of pumps other than the one I have myself (a regular Esybox). Very motivating that the integration now seems to be working (mostly) fine for Esybox, Esybox.mini and Esybox.diver.

In your attached json I spot some more values I hadn't seen before in other pumps:
- FloatEnable: 0
- FloatSwitchStatus: 255
- FluidLevel: 1058
- FluidLevel_inch: 'h'   (<-- means not applicable for your pump)
- Fluid_Remain: 6052
- Fluid_Remain_inch: 'h'
- TankFill: 62
- TankMinLev: 15
- TankMinLev_inch: 'h'
- Tank_L1_D1: 270
- Tank_L1_D1_inch: 'h'
- Tank_L2: 0
- Tank_L2_inch: 'h'

In order for me to add these properties I would need to know what unit of measurement (millimeters, meters, percentage) these values are in and what factor (i.e. divide by 10 or 1000) I need to apply.

Would it be possible for you to either:
1. open your DConnect webite or app, lookup how all of these values are presented there (or take a few screenshots) and report that back to me?

2. Or run the following script in a Home Assistant terminal window:
```
#!bash
data_usr='username=<dab portal username>'
data_pwd='password=<dab portal password'
login_htm=$(curl -j -c data/dab_cookie1.txt -k -s -L 'https://dconnect.dabpumps.com/')
login_url=$(echo "$login_htm" | grep -E -o 'action=(.*) method=' | sed -e 's/^.*action="//g' -e 's/" method=$//g' -e 's/&amp;/\&/g')

login_res=$(curl -b data/dab_cookie1.txt -c data/dab_cookie1.txt -k -s -L $login_url -H 'Content-Type: application/x-www-form-urlencoded' --data-urlencode $data_usr --data-urlencode $data_pwd)
data_inst=$(curl -b data/dab_cookie1.txt -c data/dab_cookie1.txt -k -s -L 'https://dconnect.dabpumps.com/api/v1/gui/installation/list?lang=en')

echo "$data_inst" | jq 'walk(if type=="string" and test("^{.*}$") then .|fromjson else . end)' > /config/dab_dconnect_installations.json
```
And then send the resulting dab_dconnect_installations.json to me (either as attachment to this change request, or via direct message)

**Comment by Bascht74** [comment]
I was not able to execute your script...

But I was able to download the "list?lang=en"-file with my browser and posted it here: 
https://pastebin.com/JbNY7Z70

**Comment by ankohanse** [comment]
Perfect, that is indeed exactly the installations.json that I needed!

I've added all the sensors for the Diver Fluid add-on to the integration, will publish it as a new release v.2023.12.5 tomorrow.
Let me know it you find any issues/inconsistencies with it.

**Comment by Bascht74** [comment]
Great to hear! I will try it after you published the new version.

**Comment by ankohanse** [comment]
Release v2023.12.5 is now published.
And thank you for your kind donation via BuyMeACoffee!

**Comment by Bascht74** [comment]
You are welcome!

tried the new version, restarted HA, but the sensors are not showing up… 
Removed the integration, added it again and logged on, still no change…

**Comment by Bascht74** [comment]
After another restart it worked...
I will check the sensors in the next hours...

**Comment by Bascht74** [comment]
It checked it now. 

Abnormalities: 
1. The sensor Actual period flow counter is in "L" vs. Previous month flow counter is in m³. They should have the same.
2. Sensor Saving is 0.55 and not 55%
3. Sensor Dry run detect time (TB) and Switch off delay (T2) are in seconds
4. for the new sensors: the sensor remaining water/fluid or "Fluid_Remain" is missing (must be > 3000 l). Could you add it?

Nothing more to report. Everything else worked the way it should.

Sebastian

**Comment by ankohanse** [comment]
Was able to fix the misisng Fluid_Remain.

The other three items already seem to be set to the correct unit in code. It is possible that your HA is just refusing to start using the new units because it already has historic values for the sensor in the old unit. 

To resolve this:
- Go to 'Developer Tools' and select the 'Statistics' tab. 
- I suspect there will be messages there stating something like 'The unit of this entity changed from x to y'. 
- Press the 'Fix Issue' button
- Choose between the options 'Update the unit without converting' or 'Delete all old statistic data for this entry' and press 'Fix issue'
Probably use the second option since the integration has not yet been running long and there is not much statistic data yet.

**Comment by Bascht74** [comment]
Grat! Fluid_Remain is showing up!
I changed the unit code of the other sensors.
