### ISSUE TITLE
Water consumption increasing value

### ISSUE THREAD

**Issue by domenicoblanco** [ankohanse/hass-dab-pumps#51]
**Describe the bug**
Hi, since the 4th of November I've an issue with water consumption.
The value showed by the sensor is correct, as in the attached image
<img width="560" alt="Screenshot 2024-11-25 alle 14 50 43" src="https://github.com/user-attachments/assets/c2316db6-7d56-4b1f-ad31-aa3e8dbb53a1">

But for some reason the energy dashboard shows very different values (maybe because the value is floating?)
<img width="947" alt="Screenshot 2024-11-25 alle 14 51 50" src="https://github.com/user-attachments/assets/816fe938-66fc-4669-9534-1c4867e531d9">
I think that could be a bug related to #46, as the lowest columns in the second image shows 343L, that is the correct value

**To Reproduce**
1. Go to Energy dashboard
2. Scroll down to water consumption
4. Compare with the sensor value

**Expected behavior**
That values between energy dashboard and sensor are consistent

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by domenicoblanco** [comment]
Yeah, the math is the same I applied when I thought about the floating values.
My pump is an Esybox v2 but the weird part is that I didn't change anything, both in the network or installation.
Maybe was the scheduled maintenance that happened in that period?
<img width="943" alt="Screenshot 2024-11-25 alle 21 49 42" src="https://github.com/user-attachments/assets/3a36327d-66f0-4ae1-98b2-111a36ce0492">
This is the difference with the last month and in the following is quite evident that the problem started to occur since the fourth
<img width="943" alt="Screenshot 2024-11-25 alle 21 50 18" src="https://github.com/user-attachments/assets/64fa3898-57ce-494c-a277-acf7344ec268">

**Comment by ankohanse** [comment]
I've adapted the code to be more aggressive when filtering unexpected TOTAL_INCREASING values (like going from 0.34 to 0.23)
Now released as v2024.11.4

Could you please let me know if that resolves the issue for you?

**Comment by domenicoblanco** [comment]
Of course, and thanks! 
Just restarted HA and I'll let you know!
Here is about 22:50, I'll update you tomorrow evening

**Comment by domenicoblanco** [comment]
This is a quite weird update: after more than 15 hours, it added 8m3 and then stabilised.
I don't know if is something related to their system or something to my pump, in any case I read that in the 4th of December there will be another scheduled maintenance
![Screenshot 2024-11-26 alle 18 28 45](https://github.com/user-attachments/assets/8f0a8d34-3c38-428a-970e-4e275b4db2f2)

**Comment by domenicoblanco** [comment]
After yesterday's peak it seems working normally.
Closing the issue and thanks again!
