### ISSUE TITLE
PSI off by order of magnitude

### ISSUE THREAD

**Issue by jonad0521** [ankohanse/hass-dab-pumps#7]
Great integration! One problem for me is that my pressure says 796 psi but its actually 79.6 psi. Let me know if I can help with more info. Thanks!

**Comment by ankohanse** [comment]
I'm expecting to release a major update in (the beginning of) January that should fix this. 
That version will use meta-data from the DAB Pumps Dconnect website to automatically determine things as multiplication factors (to convert from 796 psi to 79.6 psi).

I will put a comment in this issue report once that version becomes available.

**Comment by ankohanse** [comment]
Since the major update is still at least one week away, I fixed your psi values in an intermediate release (v2023.12.6) that is now available

**Comment by jonad0521** [comment]
Thanks! While the pressure values you mentioned in the release notes were fixed I think some were missed. The VP pressure and setpoint pressure remain incorrect. No worries about an intermediate release, myself at least I can gladly wait. Thanks again for the hard work.

**Comment by ankohanse** [comment]
I just released the major update (v2024.01.1), which now resolves all sensor units and weight/scale from the DAB DConnect service. That should mean they will always be identical to how they are displayed on the DAB DConnect website and app.
